<?php

//REMITOS
define ( 'ERROR_REMITO_REPETIDO', 80 );
define ( 'ERROR_REMITO_ENTREGAR', 81 );
define ( 'ERROR_REMITO_RESTRINGIDO', 82 );

//OBRAS
define ( 'ERROR_OBRA_REPETIDA', 90 );

//CONTRATISTAS
define ( 'ERROR_CONTRATISTA_REPETIDO', 100 );
//CUADRILLAS
define ( 'ERROR_CUADRILLA_REPETIDA', 101 );

//PIEZAS
define ( 'ERROR_STOCK_INSUFICIENTE', 70 );

?>